<?php
require_once 'includes/auth_check.php';
include 'header.php';

// Get user role from session
$user_role = $_SESSION['user_role'] ?? 'viewer';
$is_admin = ($user_role === 'admin');
?>

<main id="app">
    <div class="container mx-auto px-4 py-8">
        <div id="map-selection" class="mb-6">
            <div class="flex items-center justify-between mb-4">
                <h1 class="text-3xl font-bold text-white">Network Map</h1>
                <div class="flex gap-4">
                    <select id="mapSelector" class="bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 w-48"></select>
                    <?php if ($is_admin): ?>
                        <button id="newMapBtn" class="px-4 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700"><i class="fas fa-plus mr-2"></i>New Map</button>
                        <button id="renameMapBtn" class="px-4 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-500"><i class="fas fa-edit mr-2"></i>Rename</button>
                        <button id="deleteMapBtn" class="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700"><i class="fas fa-trash mr-2"></i>Delete</button>
                        <button id="mapSettingsBtn" class="px-4 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-500"><i class="fas fa-cog mr-2"></i>Settings</button>
                    <?php endif; ?>
                    <button id="shareMapBtn" class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"><i class="fas fa-share-alt mr-2"></i>Share Map</button>
                </div>
            </div>
        </div>

        <div id="map-container" class=""> <!-- Removed 'hidden' class -->
            <div id="map-controls" class="bg-slate-800 border border-slate-700 rounded-lg shadow-xl p-4 mb-6">
                <div class="flex items-center justify-between">
                    <h2 id="currentMapName" class="text-xl font-semibold text-white"></h2>
                    <div class="flex items-center gap-2">
                        <button id="refreshStatusBtn" class="px-4 py-2 bg-green-600/50 text-green-300 rounded-lg hover:bg-green-600/80" title="Refresh All Device Statuses">
                            <i class="fas fa-sync-alt"></i>
                        </button>
                        <label class="flex items-center text-slate-400">
                            <input type="checkbox" id="liveRefreshToggle" class="form-checkbox h-5 w-5 text-cyan-600 rounded border-slate-500 bg-slate-700 focus:ring-cyan-500">
                            <span class="ml-2 text-sm">Live Refresh</span>
                        </label>
                        <?php if ($is_admin): ?>
                            <a href="create-device.php" id="addDeviceBtn" class="px-4 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700"><i class="fas fa-plus mr-2"></i>Add Device</a>
                            <button id="placeDeviceBtn" class="px-4 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-500"><i class="fas fa-map-pin mr-2"></i>Place Device</button>
                            <button id="addEdgeBtn" class="px-4 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-500"><i class="fas fa-link mr-2"></i>Add Connection</button>
                            <button id="scanNetworkBtn" class="px-4 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-500"><i class="fas fa-wifi mr-2"></i>Scan Network</button>
                            <button id="exportBtn" class="px-4 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-500"><i class="fas fa-file-export mr-2"></i>Export Map</button>
                            <input type="file" id="importFile" class="hidden" accept="application/json">
                            <button id="importBtn" class="px-4 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-500"><i class="fas fa-file-import mr-2"></i>Import Map</button>
                        <?php endif; ?>
                        <button id="fullscreenBtn" class="px-4 py-2 bg-slate-600 text-white rounded-lg hover:bg-slate-500" title="Toggle Fullscreen">
                            <i class="fas fa-expand"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div id="network-map-wrapper">
                <div id="network-map"></div>
                <div id="context-menu" class="context-menu"></div>
                <div id="status-legend">
                    <!-- Legend items are now generated by map.js -->
                </div>
            </div>
        </div>
        
        <div id="no-maps" class="text-center py-16 bg-slate-800 border border-slate-700 rounded-lg hidden">
            <i class="fas fa-map-signs text-slate-600 text-5xl mb-4"></i>
            <h2 class="text-2xl font-bold text-white mb-2">No Network Maps Found</h2>
            <p class="text-slate-400 mb-6">Create a map to start visualizing your network.</p>
            <button id="createFirstMapBtn" class="px-6 py-3 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700 text-lg" <?= $is_admin ? '' : 'disabled' ?>>Create Your First Map</button>
        </div>
    </div>

    <!-- Modals -->
    <div id="edgeModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-md border border-slate-700">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-2xl font-semibold text-white">Edit Connection</h2>
                <button onclick="closeModal('edgeModal')" class="text-slate-400 hover:text-white text-2xl">&times;</button>
            </div>
            <form id="edgeForm" class="space-y-4">
                <input type="hidden" id="edgeId">
                <div>
                    <label for="connectionType" class="block text-sm font-medium text-slate-400 mb-1">Connection Type</label>
                    <select id="connectionType" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500">
                        <option value="cat5">CAT5/Ethernet</option>
                        <option value="fiber">Fiber Optic</option>
                        <option value="wifi">Wi-Fi</option>
                        <option value="radio">Radio Link</option>
                    </select>
                </div>
                <div class="flex justify-end gap-4">
                    <button type="button" id="cancelEdgeBtn" class="px-4 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600">Cancel</button>
                    <button type="submit" class="px-4 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700">Save Changes</button>
                </div>
            </form>
        </div>
    </div>

    <div id="scanModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-md border border-slate-700">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-2xl font-semibold text-white">Network Scanner</h2>
                <button id="closeScanModal" class="text-slate-400 hover:text-white text-2xl">&times;</button>
            </div>
            <form id="scanForm" class="flex gap-2 mb-4">
                <input type="text" id="subnetInput" placeholder="e.g., 192.168.1.0/24" value="192.168.1.0/24" class="flex-1 bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500">
                <button type="submit" class="px-4 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700"><i class="fas fa-search mr-2"></i>Scan</button>
            </form>
            <div id="scanInitialMessage" class="text-center text-slate-500 py-4">
                Enter a subnet (e.g., 192.168.1.0/24) and click Scan to find devices.
            </div>
            <div id="scanLoader" class="text-center py-8 hidden"><div class="loader mx-auto"></div></div>
            <div id="scanResults" class="max-h-60 overflow-y-auto space-y-2"></div>
        </div>
    </div>

    <div id="placeDeviceModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-md border border-slate-700">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-2xl font-semibold text-white">Place Unassigned Device</h2>
                <button id="closePlaceDeviceModal" class="text-slate-400 hover:text-white text-2xl">&times;</button>
            </div>
            <p class="text-slate-400 mb-4">Select a device to place it on the current map.</p>
            <div id="placeDeviceLoader" class="text-center py-8 hidden"><div class="loader mx-auto"></div></div>
            <div id="placeDeviceList" class="max-h-60 overflow-y-auto">
                <!-- Unassigned devices will be loaded here -->
            </div>
        </div>
    </div>

    <div id="mapSettingsModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-md border border-slate-700">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-2xl font-semibold text-white">Map Settings</h2>
                <button id="closeMapSettingsModal" onclick="closeModal('mapSettingsModal')" class="text-slate-400 hover:text-white text-2xl">&times;</button>
            </div>
            <form id="mapSettingsForm" class="space-y-4">
                <div>
                    <label for="mapBgColor" class="block text-sm font-medium text-slate-400 mb-1">Background Color</label>
                    <div class="flex items-center gap-2">
                        <input type="color" id="mapBgColor" value="#1e293b" class="h-10 w-14 p-1 cursor-pointer">
                        <input type="text" id="mapBgColorHex" name="background_color" value="#1e293b" placeholder="#1e293b" class="flex-1 bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500">
                    </div>
                </div>
                <div>
                    <label for="mapBgImageUrl" class="block text-sm font-medium text-slate-400 mb-1">Background Image URL</label>
                    <input type="text" id="mapBgImageUrl" name="background_image_url" placeholder="Leave blank for no image" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500">
                </div>
                <div class="text-center text-slate-500 text-sm">OR</div>
                <div>
                    <label for="mapBgUpload" class="block text-sm font-medium text-slate-400 mb-1">Upload Background Image</label>
                    <input type="file" id="mapBgUpload" accept="image/*" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-cyan-600/20 file:text-cyan-300">
                    <div id="mapBgUploadLoader" class="text-center py-2 hidden">
                        <i class="fas fa-spinner fa-spin text-cyan-400 text-xl"></i>
                        <span class="ml-2 text-slate-300">Uploading...</span>
                    </div>
                </div>
                <div class="border-t border-slate-700 pt-4 mt-4 space-y-3">
                    <h3 class="text-lg font-semibold text-white">Public View Settings</h3>
                    <label class="flex items-center text-sm font-medium text-slate-400">
                        <input type="checkbox" id="publicViewToggle" name="public_view_enabled" class="form-checkbox h-5 w-5 text-cyan-600 rounded border-slate-500 bg-slate-700 focus:ring-cyan-500">
                        <span class="ml-2">Enable Public View</span>
                    </label>
                    <p class="text-sm text-slate-500">Allow anyone with the link to view this map without logging in.</p>
                    <div id="publicViewLinkContainer" class="space-y-2 hidden">
                        <label for="publicViewLink" class="block text-sm font-medium text-slate-400 mb-1">Public Link:</label>
                        <div class="flex items-center gap-2">
                            <input type="text" id="publicViewLink" readonly class="flex-1 bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 text-white">
                            <button type="button" id="copyPublicLinkBtn" class="px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"><i class="fas fa-copy"></i></button>
                        </div>
                    </div>
                </div>
                <div class="flex justify-between items-center gap-4 mt-6">
                    <button type="button" id="resetMapBgBtn" class="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700"><i class="fas fa-undo mr-2"></i>Reset to Default</button>
                    <div class="flex gap-2">
                        <button type="button" id="cancelMapSettingsBtn" class="px-4 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600">Cancel</button>
                        <button type="submit" class="px-4 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700">Save Changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <!-- Custom Confirmation Modal -->
    <div id="confirmModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-sm border border-slate-700">
            <div class="flex items-center justify-between mb-4">
                <h2 id="confirmModalTitle" class="text-xl font-semibold text-white">Confirm Action</h2>
                <button onclick="closeModal('confirmModal')" class="text-slate-400 hover:text-white text-2xl">&times;</button>
            </div>
            <p id="confirmModalMessage" class="text-slate-300 mb-6">Are you sure you want to proceed?</p>
            <div class="flex justify-end gap-4">
                <button type="button" id="confirmModalCancelBtn" onclick="closeModal('confirmModal')" class="px-4 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600">Cancel</button>
                <button type="button" id="confirmModalConfirmBtn" class="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700">Confirm</button>
            </div>
        </div>
    </div>

    <!-- Custom Input Modal -->
    <div id="inputModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-sm border border-slate-700">
            <div class="flex items-center justify-between mb-4">
                <h2 id="inputModalTitle" class="text-xl font-semibold text-white">Enter Value</h2>
                <button onclick="closeModal('inputModal')" class="text-slate-400 hover:text-white text-2xl">&times;</button>
            </div>
            <p id="inputModalMessage" class="text-slate-300 mb-4">Please enter the required information:</p>
            <input type="text" id="inputModalField" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white mb-6">
            <div class="flex justify-end gap-4">
                <button type="button" id="inputModalCancelBtn" onclick="closeModal('inputModal')" class="px-4 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600">Cancel</button>
                <button type="button" id="inputModalConfirmBtn" class="px-4 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700">Submit</button>
            </div>
        </div>
    </div>
</main>

<?php include 'footer.php'; ?>