<?php
require_once 'includes/auth_check.php';
include 'header.php';

// Get user role from session
$user_role = $_SESSION['user_role'] ?? 'viewer';
$is_admin = ($user_role === 'admin');
?>

<main id="app">
    <div class="container mx-auto px-4 py-8">
        <div id="map-selection" class="mb-6">
            <div class="flex items-center justify-between mb-4">
                <h1 class="text-3xl font-bold text-white">Network Map</h1>
                <div class="flex gap-4">
                    <!-- Map selection and management buttons are now handled by the React component -->
                    <!-- This PHP page will primarily serve the React app, so these controls are removed -->
                </div>
            </div>
        </div>

        <div id="map-container" class="hidden">
            <div id="map-controls" class="bg-slate-800 border border-slate-700 rounded-lg shadow-xl p-4 mb-6">
                <div class="flex items-center justify-between">
                    <h2 id="currentMapName" class="text-xl font-semibold text-white"></h2>
                    <div class="flex items-center gap-2">
                        <!-- Map controls are now handled by the React component -->
                    </div>
                </div>
            </div>
            <div id="network-map-wrapper">
                <div id="network-map"></div>
                <div id="context-menu" class="context-menu"></div>
                <div id="status-legend">
                    <!-- Legend items are now generated by map.js -->
                </div>
            </div>
        </div>
        
        <div id="no-maps" class="text-center py-16 bg-slate-800 border border-slate-700 rounded-lg hidden">
            <i class="fas fa-map-signs text-slate-600 text-5xl mb-4"></i>
            <h2 class="text-2xl font-bold text-white mb-2">No Network Maps Found</h2>
            <p class="text-slate-400 mb-6">Create a map to start visualizing your network.</p>
            <button id="createFirstMapBtn" class="px-6 py-3 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700 text-lg" <?= $is_admin ? '' : 'disabled' ?>>Create Your First Map</button>
        </div>
    </div>

    <!-- Modals -->
    <!-- All modals are now handled by React components -->
</main>

<?php include 'footer.php'; ?>