<?php
require_once __DIR__ . '/includes/auth.php';
ampnm_require_auth();
require_once __DIR__ . '/includes/layout.php';

$pdo = ampnm_pdo();
$notifications = [];
try {
    $stmt = $pdo->query('SELECT title, body, severity, created_at FROM notifications ORDER BY created_at DESC LIMIT 25');
    $notifications = $stmt->fetchAll();
} catch (Throwable $e) {
    $notifications = [];
}

renderPageStart('Notifications', 'notifications');
?>
<section class="card">
    <h2>Recent notifications</h2>
    <p class="muted">Latest alerts generated by monitors and device checks.</p>
    <div class="timeline">
        <?php if (empty($notifications)): ?>
            <div class="timeline-item">No alerts yet. Run a ping or add a device to generate history.</div>
        <?php else: ?>
            <?php foreach ($notifications as $note): ?>
                <div class="timeline-item">
                    <div class="badge badge-<?php echo htmlspecialchars($note['severity']); ?>"><?php echo htmlspecialchars(strtoupper($note['severity'])); ?></div>
                    <strong><?php echo htmlspecialchars($note['title']); ?></strong>
                    <div class="muted"><?php echo htmlspecialchars($note['body'] ?? ''); ?></div>
                    <small class="muted"><?php echo htmlspecialchars($note['created_at']); ?></small>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</section>
<section class="card">
    <h2>Simulate alert</h2>
    <p class="muted">Quickly add a test notification to ensure the table and UI are working.</p>
    <form method="post" class="grid two">
        <div class="form-group" style="grid-column:1 / -1;">
            <label class="label">Title</label>
            <input class="input" name="title" placeholder="Port 443 open on Firewall">
        </div>
        <div class="form-group" style="grid-column:1 / -1;">
            <label class="label">Body</label>
            <textarea class="input" name="body" rows="3" placeholder="HTTPS is reachable with 40ms latency"></textarea>
        </div>
        <div class="form-group">
            <label class="label">Severity</label>
            <select class="input" name="severity">
                <option value="info">Info</option>
                <option value="warning">Warning</option>
                <option value="critical">Critical</option>
            </select>
        </div>
        <button class="btn" type="submit">Save alert</button>
    </form>
</section>
<?php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $title = trim($_POST['title'] ?? 'Manual alert');
    $body = trim($_POST['body'] ?? '');
    $severity = trim($_POST['severity'] ?? 'info');
    try {
        $stmt = $pdo->prepare('INSERT INTO notifications (title, body, severity) VALUES (:title, :body, :severity)');
        $stmt->execute([
            ':title' => $title,
            ':body' => $body,
            ':severity' => $severity ?: 'info',
        ]);
        header('Location: ' . ampnm_base_url() . '/notifications.php');
        exit;
    } catch (Throwable $e) {
        echo '<div class="alert alert-error">Could not save notification: ' . htmlspecialchars($e->getMessage()) . '</div>';
    }
}
renderPageEnd();
?>
